export const ClsTypes = Object.freeze({
  article: 'Article',
  article_journal: 'Article Journal',
  article_magazine: 'Article Magazine',
  article_newspaper: 'Article Newspaper',
  bill: 'Bill',
  book: 'Book',
  broadcast: 'Broadcast',
  chapter: 'Chapter',
  classic: 'Classic',
  collection: 'Collection',
  dataset: 'Dataset',
  document: 'Document',
  entry: 'Entry',
  entry_dictionary: 'Entry Dictionary',
  entry_encyclopedia: 'Entry Encyclopedia',
  event: 'Event',
  figure: 'Figure',
  graphic: 'Graphic',
  hearing: 'Hearing',
  interview: 'Interview',
  legal_case: 'Legal Case',
  legislation: 'Legislation',
  manuscript: 'Manuscript',
  map: 'Map',
  motion_picture: 'Motion Picture',
  musical_score: 'Musical Score',
  pamphlet: 'Pamphlet',
  paper_conference: 'Paper Conference',
  patent: 'Patent',
  performance: 'Performance',
  periodical: 'Periodical',
  personal_communication: 'Personal Communication',
  post: 'Post',
  post_weblog: 'Post Weblog',
  regulation: 'Regulation',
  report: 'Report',
  review: 'Review',
  review_book: 'Review Book',
  software: 'Software',
  song: 'Song',
  speech: 'Speech',
  standard: 'Standard',
  thesis: 'Thesis',
  treaty: 'Treaty',
  webpage: 'Webpage',
});