# Generated by Django 5.1.7 on 2025-04-15 19:40

import intertidal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intertidal', '0003_alter_occurrence_options_person_bio_resourceaudio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='person',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='genres',
        ),
        migrations.AlterField(
            model_name='organization',
            name='alternative_names',
            field=intertidal.models.AlternativeNamesArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='alternative_names',
            field=intertidal.models.AlternativeNamesArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='resource',
            name='alternative_names',
            field=intertidal.models.AlternativeNamesArrayField(base_field=models.CharField(), blank=True, default=list, size=None, verbose_name='Alternative Names/Titles'),
        ),
    ]
