# Generated by Django 6.0.1 on 2026-07-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intertidal_app', '0006_resourceaudio_audio_resourceaudio_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceimage',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='resourceimage',
            name='image_width',
        ),
        migrations.RemoveField(
            model_name='resourceimage',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, help_text='Please use <u><a href="https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types" target="_blank">standard web image types</a></u>. PNG, JPEG, and WebP are recommended.', null=True, upload_to='images/', verbose_name='Headshot'),
        ),
        migrations.AlterField(
            model_name='resourceimage',
            name='image',
            field=models.ImageField(help_text='Please use <u><a href="https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types" target="_blank">standard web image types</a></u>. PNG, JPEG, and WebP are recommended.', upload_to='images/'),
        ),
    ]
