# Generated by Django 6.0.1 on 2026-08-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intertidal_app', '0007_remove_resourceimage_image_height_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edition',
            options={'ordering': ['date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='occurrence',
            options={'ordering': ['date', 'id'], 'verbose_name': 'Special Occurrence'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='resourceaudio',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='resourceimage',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='resourceaudio',
            name='audio_snippet',
            field=models.FileField(blank=True, help_text='Please use <u><a href="https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers" target="_blank">standard web audio types</a></u>. MP3 (.mp3), AAC (.m4a), WAV (.wav), or Ogg (.ogg) are recommended.', null=True, upload_to='audio/', verbose_name='Audio Snippet'),
        ),
    ]
